
# test:
#   container_name: sailsSample_test
#   image: miiixr/picklete_env
#   extends:
#     file: ./dockerConfig/development.yml
#     service: test
#
#   external_links:
#
#     - mysql
#
#   working_dir: /picklete
#   volumes:
#     - ./:/picklete
#
# mysql:
#   container_name: mysql
#   image: dgraziotin/mysql
#   extends:
#     file: ./dockerConfig/development.yml
#     service: mysql
#   volumes:
#     - ../database:/var/lib/mysql/
#
#   restart: always

build:
  container_name: trademuch-build
  image: miiixr/picklete_env
  command: "/bin/bash -l -c 'npm i | grunt build'"
  working_dir: /app
  volumes:
    - ./:/app

buildProd:
  container_name: trademuch-build
  image: node:4
  command: "/bin/bash -l -c 'npm i | ./node_modules/grunt-cli/bin/grunt prod --force'"
  working_dir: /app
  volumes:
    - ./:/app

test:
  container_name: trademuch-test
  image: miiixr/picklete_env
  command: "/bin/bash -l -c 'npm i | npm test'"
  environment:
    NODE_ENV: "test"
  working_dir: /app
  volumes:
    - ./:/app

web:
  container_name: trademuch
  image: miiixr/picklete_env
  command: "/bin/bash -l -c 'npm start'"
  ports:
    - "1333:1337"
  working_dir: /app
  volumes:
    - ./:/app
  external_links:
    - mysql

  restart: always

elasticsearch:
  container_name: elasticsearch
  image:  elasticsearch:2.2.0
  ports:
    - "9200:9200"
    - "9300:9300"

elasticsearch_prod:
  container_name: elasticsearch_prod
  image:  elasticsearch:2.2.0
  ports:
    - "9299:9200"
    - "9399:9300"
